name: ground_guard_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-216.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  mobile_scanner: ^5.2.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launch_icon_light.png"
  image_path_ios_dark: "assets/images/launch_icon_dark.png"
  image_path_ios_tinted: "assets/images/launch_icon_dark.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/launch_icon_light.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json_icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-Italic.ttf
          weight: 400
          style: italic
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
