#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/opt/homebrew/share/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/guilherme/developer/flutter/ground_guard_app"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/guilherme/developer/flutter/ground_guard_app/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/guilherme/developer/flutter/ground_guard_app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9WRVJTSU9OPTMuNDUuMC0xLjAucHJlLTI3MA==,RkxVVFRFUl9DSEFOTkVMPW1hc3Rlcg==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049OTFkNmVmNjk0Mg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049OTFkNmVmNjk0Mg==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMy4wIChidWlsZCAzLjEzLjAtMTQ2LjAuZGV2KQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/guilherme/developer/flutter/ground_guard_app/.dart_tool/package_config.json"
